### ISSUE TITLE
Error message for unknown variables should be fixed

### ISSUE THREAD

**Issue by schubertr** [TeamShadow/shadow#17]
If you mistype a variable name or something, and then try and do something with it, you get an invalid type error:

    Invalid type: Operator not defined on types int and Unknown Type

Since you are getting this error because you are trying to use a variable that doesn't exist, shouldn't you get something like this (C error for the same issue):

    Error: use of undeclared identifier

**Comment by bwittman** [comment]
Can you post code that causes this error?

I tried the following:
```
class Test
{
	public main() => ()
	{
		int a = 5;
		a = 3 + b;
	}
}
```
But I get the (relatively helpful) error:
```
Undefined type: Type b not defined in this context
```

**Comment by schubertr** [comment]
Here is the code:

        import shadow:io@Console;
        
        class bits
        {
            public main( String[] args ) => ()
            {
            	String temp;
            	Console con = Console:instance;
            	
            	con.print("\nEnter an Integer: ");
               	(temp, ) = con.readLine();
               	con.printLine();
               	int num = temp.toInt();
               	
               	con.print("Do you want to set, unset, or flip a bit? (s, u, f): ");
               	(temp, ) = con.readLine();
               	con.printLine();
               	code choice = temp->codes[0];
               	
               	con.print("Which bit? (0-31): ");
               	(temp, ) = con.readLine();
               	con.printLine();
               	int bit = temp.toInt();
               	
               	if(choice == 's')
               		bitset(num, bit);
               	
               	else if(choice == 'u')
               		unset(num, bit);
               		
               	else if(choice == 'f')
               		flip(num, bit);
            }
            
            public bitset(int num, int bit) => ()
            {
            	Console con = Console:instance;
            	
            	int temp = 1 << bit;
            	int new = temp | value;
            	con.printLine("The result of setting bit " # bit # " in " # num # " is " # new # ".\n");
            	
            }
            
            public unset(int num, int bit) => ()
            {
            	Console con = Console:instance;
            	
            	int temp = 1 << bit;
            	temp = ~temp;
            	int new = temp & value;
            	con.printLine("The result of unsetting bit " # bit # " in " # num # " is " # new # ".\n");
            }
            
            public flip(int num, int bit) => ()
            {
            	Console con = Console:instance;
            	
            	int temp = 1 << bit;
            	int new = temp ^ value;
            	con.printLine("The result of unsetting bit " # bit # " in " # num # " is " # new # ".\n");
            }
        }
        

Note that in each helper method (bitset, unset, and flip), I use a variable called value (it should be num instead) which is not declared anywhere. If you run this, you'll get these errors:

    [ERROR BaseChecker.java:376] (bits.shadow)[40:26] Undefined type: Type value not defined in this context
    [ERROR BaseChecker.java:376] (bits.shadow)[40:19] Invalid method: No definition of bitOr with arguments (Unknown Type) in this context
    [ERROR BaseChecker.java:376] (bits.shadow)[40:19] Invalid type: Operator | not defined on types int and Unknown Type
    [ERROR BaseChecker.java:376] (bits.shadow)[51:26] Undefined type: Type value not defined in this context
    [ERROR BaseChecker.java:376] (bits.shadow)[51:19] Invalid method: No definition of bitAnd with arguments (Unknown Type) in this context
    [ERROR BaseChecker.java:376] (bits.shadow)[51:19] Invalid type: Operator & not defined on types int and Unknown Type
    [ERROR BaseChecker.java:376] (bits.shadow)[60:26] Undefined type: Type value not defined in this context
    [ERROR BaseChecker.java:376] (bits.shadow)[60:19] Invalid method: No definition of bitXor with arguments (Unknown Type) in this context
    [ERROR BaseChecker.java:376] (bits.shadow)[60:19] Invalid type: Operator ^ not defined on types int and Unknown Type
    [ERROR Main.java:250] /Users/Ryan/Desktop/Git/shadowProjects/Bits/Bits.shadow FAILED TO TYPE CHECK
    TYPE CHECK ERROR: (bits.shadow)[40:26] Undefined type: Type value not defined in this context

**Comment by bwittman** [comment]
I think the new .jar file should fix this as well.

**Comment by schubertr** [comment]
These are the errors I get now, these seem to be correct but I just wanted to verify.

    [ERROR] (ArrayDeque.shadow)[60:32] Invalid type: Non-nullable expression cannot be used in a check statement
    [ERROR] (ArrayDeque.shadow)[75:32] Invalid type: Non-nullable expression cannot be used in a check statement
    [ERROR] (ArrayDeque.shadow)[90:34] Invalid type: Non-nullable expression cannot be used in a check statement
    [ERROR] (ArrayDeque.shadow)[108:34] Invalid type: Non-nullable expression cannot be used in a check statement
    [ERROR] (ArrayDeque.shadow)[177:42] Invalid type: Non-nullable expression cannot be used in a check statement
    [ERROR] /Users/Ryan/Desktop/Git/shadowProjects/Bits/Bits.shadow FAILED TO TYPE CHECK
    TYPE CHECK ERROR: (ArrayDeque.shadow)[60:32] Invalid type: Non-nullable expression cannot be used in a check statement

**Comment by schubertr** [comment]
I still get the same errors for this one.

    [ERROR] (bits.shadow)[40:26] Undefined type: Type value not defined in this context
    [ERROR] (bits.shadow)[40:19] Invalid method: No definition of bitOr with arguments (Unknown Type) in this context
    [ERROR] (bits.shadow)[40:19] Invalid type: Operator | not defined on types int and Unknown Type
    [ERROR] (bits.shadow)[51:26] Undefined type: Type value not defined in this context
    [ERROR] (bits.shadow)[51:19] Invalid method: No definition of bitAnd with arguments (Unknown Type) in this context
    [ERROR] (bits.shadow)[51:19] Invalid type: Operator & not defined on types int and Unknown Type
    [ERROR] (bits.shadow)[60:26] Undefined type: Type value not defined in this context
    [ERROR] (bits.shadow)[60:19] Invalid method: No definition of bitXor with arguments (Unknown Type) in this context
    [ERROR] (bits.shadow)[60:19] Invalid type: Operator ^ not defined on types int and Unknown Type
    [ERROR] /Users/Ryan/Desktop/Git/shadowProjects/Bits/Bits.shadow FAILED TO TYPE CHECK

**Comment by schubertr** [comment]
I'm going to close this. The error was just because I wasn't paying attention and didn't write this code correctly. Notice it doesn't like when it tries to do something to "value". The reason this was happening is because I never declared "value". Everywhere it says "value", it should be "num" instead. That's what I get for copying and pasting...
